services:
  api:
    build: ./api
    container_name: api
    restart: unless-stopped
    ports:
      - '3000:3000'
    depends_on:
      - rabbitmq
      - redis
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
    networks:
      - app-network

  text2sql-worker:
    build: ./text2sql-worker
    container_name: text2sql-worker
    restart: unless-stopped
    environment:
      - REDIS_HOST=redis
      - RABBITMQ_HOST=rabbitmq
      - MODEL_PATH=/models/Chat2DB-SQL-7B
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          memory: 12g
    depends_on:
      - redis
      - rabbitmq
    networks:
      - app-network

  rabbitmq:
    image: 'rabbitmq:3-management'
    container_name: rabbitmq
    restart: unless-stopped
    ports:
      - '5672:5672'
      - '15672:15672'
    healthcheck:
      test: ["CMD-SHELL", "rabbitmq-diagnostics -q ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - app-network

  redis:
    image: 'redis:alpine'
    container_name: redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
